version: "3.8"

services:
  app:
    image: stripe-wrapper
    container_name: stripe-wrapper
    build:
      context: .
      target: development
    env_file: 
      - .docker.env
      - .env
    tty: true
    stdin_open: true
    ports:
      - 3001:3000
    tmpfs:
      - /app/tmp/pids
      - /app/tmp/cache
    depends_on:
      - postgres
    volumes:
      - ./:/app:c
      - bundle:/usr/local/bundle:d
      - node_modules:/usr/local/bundle:d
      - data:/data:d
    healthcheck:
      test: ["CMD", "curl", "http://app:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    command: bundle exec puma -C config/puma.rb

  test:
    image: stripe-wrapper
    container_name: stripe-wrapper-test
    env_file: 
      - .docker.env
      - .env
    environment:
      - RAILS_ENV=test
      - RACK_ENV=test
    tmpfs:
      - /app/tmp/pids
      - /app/tmp/cache
    depends_on:
      - postgres
    volumes:
      - ./:/app:c
      - bundle:/usr/local/bundle:d
      - node_modules:/usr/local/bundle:d
      - data:/data:d
    healthcheck:
      test: ["CMD", "curl", "http://app:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  postgres:
    image: postgres:14.0
    container_name: stripewrapper-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: 0.0.0.0
    volumes:
      - postgres:/var/lib/postgresql/data:c
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h postgres -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # mailcatcher:
  #   image: dockage/mailcatcher
  #   container_name: stripewrapper-mailcatcher
  #   restart: on-failure:10
  #   ports:
  #     - 1080:1080

volumes:
  postgres:
  redis:
  bundle:
  node_modules:
  data: