default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV.fetch("DATABASE_URL") { "postgres://localhost:5432" } %>

development:
  <<: *default
  database: stripewrapper_development

test:
  <<: *default
  database: stripewrapper_test

production:
  <<: *default
  url: stripewrapper_production